### PR TITLE
Extract signatures from commits, fixes #56

### LINKED ISSUE #56: Extract Signature
A `Commit` signature can be retrieved via [`extract_signature`](https://docs.rs/git2/0.11.0/git2/struct.Repository.html#method.extract_signature). This will need to be added to the data of a commit, or else as a function in surf.

### PR DESCRIPTION
**Pull request by alexjg**

### CODE REVIEW

**Comment by alexjg** [comment]
Picked this one up as it looked like a good place to start getting involved. As far as I can tell the build failure is due to the build server having run out of space?

**Comment by FintanH** [comment]
>  As far as I can tell the build failure is due to the build server having run out of space?

Ya it looks like it. I'll figure this out for you in the meantime :)

**Comment by alexjg** [comment]
I went for `browser.extract_signature` for the name, just for consistency with the git naming, does that work?

**Comment by FintanH** [comment]
> I went for browser.extract_signature for the name, just for consistency with the git naming, does that work?

Makes total sense :ok_hand:

> Ya it looks like it. I'll figure this out for you in the meantime :)

We figured out the cache volume issue. Just need to put a fix in place :)

**Comment by alexjg** [comment]
Ah I wondered what all that git-platinum stuff was. Doctest added.

**Comment by FintanH** [comment]
> Ah I wondered what all that git-platinum stuff was. Doctest added. 

Amazing! Sorry for the back-and-forth, here's my last request I PROMISE. We have a commit in `git-platinum` now that doesn't have a signature: https://github.com/radicle-dev/git-platinum/commit/80bacafba303bf0cdf6142921f430ff265f25095 so if you could test that out we'll be all gravy.

Also, I'd like to move the doc tests to use this form https://rust-lang.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark. So if you could use this form for the one you're adding that'd be awesome :)

**Comment by alexjg** [comment]
No problem, I actually really enjoy the back and forth, it's a similar feeling to the feeling of polishing a finished piece of woodwork, like making everything perfect :slightly_smiling_face: 

Negative doctest and `?` example added.

**Comment by FintanH** [comment]
For some reason, this [build](https://buildkite.com/monadic/radicle-surf/builds/202) isn't getting picked up here. But since there's one build on CI passing I'm happy to merge this :)

**Pull request merged**
