### PR TITLE
Replace 'expect' and 'unwrap' with '?' in doctests

### LINKED ISSUE #77: Error Tests
[This](https://rust-lang.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark) is soooo much better than using `expect` and `unwrap` in tests. Let's clean them up making our docs a lot better!

### PR DESCRIPTION
**Pull request by sonro**
In doctests where there could be an error, use the '?' operator in line with [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark). 

Update README example to match this change, as well as previous changes to the lib.rs example.

I have chosen to leave Option unwraps/expects for simplicity.

Fixes #77

### CODE REVIEW

**Comment by FintanH** [comment]
@sonro Could you rebase `master`? I wasn't pinning the images correctly and this should fix it from trying to build the image and running into this CI error :crossed_fingers:

**Comment by sonro** [comment]
@FintanH, I rebased and pushed but still getting a buildkite error. Let me know if there is anything more I can do from my end.

**Comment by FintanH** [comment]
Thanks, @sonro :grin: That was another unrelated error :sweat_smile: 

While we're here, I'm not sure if you're on our Discourse but I gave you a [shoutout](https://radicle.community/t/radicle-surf-contributions/151/3). Thanks for extra help :heart:

**Comment by abbey-titcomb** [comment]
Hey @sonro ! Any chance you could send me an email at abbey@monadic.xyz? We've just changed our licensing strategy for Radicle and need to get a DCO from you. Cheers!

**Pull request merged**
